apiVersion: v1
kind: Service
metadata:
  # labe:
  #   app: elasticsearch
  name: elasticsearch-discovery
  namespace: default
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  type: ClusterIP
  sessionAffinity: None